version: "3.8"
services:
  app:
    container_name: gb-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_PATH=http://gb-api:5000
    ports:
      - "3000:3000"
